name: "Rickroll CI"
description: "Rickroll quand votre mutation score drop"

runs:
  using: "composite"
  steps:
    - run: |
        echo "ðŸŽµ Never gonna give you up ðŸŽµ"
        echo "https://youtu.be/dQw4w9WgXcQ"
