name: Mutation Testing

on:
  push:
    paths:
      - "core/**"
      - ".github/workflows/mutation.yml"
  pull_request:
    paths:
      - "core/**"
      - ".github/workflows/mutation.yml"

jobs:
  pitest:
    runs-on: ubuntu-latest

    outputs:
      drop: ${{ steps.compare.outputs.drop }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build all modules first (required by Maven)
        run: mvn -q clean install -DskipTests

      - name: Run PIT on core only
        run: |
          cd core
          mvn -DwithHistory org.pitest:pitest-maven:mutationCoverage

      - name: Extract mutation score
        id: extract
        run: |
          file=$(find core/target -type f -name "mutations.xml" | head -n 1)
          echo "Found file: $file"

          if [ -z "$file" ]; then
            echo "score=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          score=$(grep -oP '(?<=<mutationCoverage>).*(?=</mutationCoverage>)' "$file")
          echo "score=$score" >> $GITHUB_OUTPUT
      

      - name: Compare with previous score
        id: compare
        run: |
          current=${{ steps.extract.outputs.score }}
          previous=$(cat .mutation-baseline 2>/dev/null || echo 0)

          echo "Previous score: $previous%"
          echo "Current score : $current%"

          if (( $(echo "$current < $previous" | bc -l) )); then
            echo "drop=true" >> $GITHUB_OUTPUT
          else
            echo "drop=false" >> $GITHUB_OUTPUT
            echo "$current" > .mutation-baseline
          fi

      - name: Commit updated baseline
        if: steps.compare.outputs.drop == 'false'
        run: |
          git config --local user.email "ci@example.com"
          git config --local user.name "CI BOT"
          git add .mutation-baseline
          git commit -m "Update mutation baseline" || echo "No changes"

  rickroll:
    needs: pitest
    runs-on: ubuntu-latest

    # Rickroll se déclenche si :
    # - le job pitest fail (tests cassés)
    # - le score diminue (drop=true)
    if: |
      needs.pitest.result == 'failure' ||
      needs.pitest.outputs.drop == 'true'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Rickroll
        uses: ./.github/actions/rickroll
